swagger: "2.0"
info:
  version: "1.0.0"
  title: "FIR_Demo_Service"
  contact:
    email: "analysta20@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "localhost"
basePath: "/"
tags:
- name: "FIRComplaints"
  description: "Your FIRPortal"
schemes:
- "http"
paths:
  /FIR:
    get:
      tags:
      - "FIRComplaints"
      summary: "Get all FIRComplaints from the box"
      operationId: "getAllFIR"
      security:
      - oauth2: [global]
      produces:
      - "application/json"
      responses:
        200:
          description: "list of all FIR's"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/FIR"
    post:
      tags:
      - "FIRComplaints"
      summary: "Add a new Complaint to the box"
      operationId: "addNewComplaint"
      parameters:
      - in: "body"
        name: "body"
        description: "Complaint object that needs to be added to the box"
        required: true
        schema:
          type: "object"
          properties:
            district:
              type: "string"
            state:
              type: "string"
            policeStation:
              type: "string"
            fIRno:
              type: "string"
            date:
              type: "string"
            act1:
              type: "string"
            sections1:
              type: "string"
            act2:
              type: "string"
            sections2:
              type: "string"
            act3:
              type: "string"
            sections3:
              type: "string"
            otherActsAndSections:
              type: "string"
            occurenceDay:
              type: "string"
            occurenceDate:
              type: "string"
            occurenceTime:
              type: "string"
            informatioReceivedDate: 
              type: "string"
            informatioReceivedTime: 
              type: "string"
            diaryReferenceEntryNo: 
              type: "string"
            diaryReferenceTime: 
              type: "string"
            written: 
              type: "string"
            oral: 
              type: "string"
            directionAndDistncefromPS:
              type: "string"
            beatNo: 
              type: "string"
            address: 
              type: "string"
            outsideNameofPSAndDistrict: 
              type: "string"
            complainantName: 
              type: "string"
            complainantFatherorHusbandName: 
              type: "string"
            complainantDateOfBirth: 
             type: "string"
            complainantNationality: 
              type: "string"
            complainantOccupation: 
              type: "string"
            complainantPassportNo: 
              type: "string"
            complainantDateofIssue: 
              type: "string"
            complainantPlaceOfIssue: 
              type: "string"
            complainantAddress: 
              type: "string"
            detailsOfSuspected: 
              type: "string"
            reasonsforDelay: 
              type: "string"
            particularsOfPropertiesStolenInvolved: 
              type: "string"
      security:
      - oauth2: [global]
      consumes:
      - "application/json"
      responses:
        201:
          description: "Complaint was created"
        400:
          description: "Complaint object format mismatch"
  /FIR/{FIRId}:
    get:
      tags:
      - "FIRComplaints"
      summary: "Get FIRComplaint by id"
      operationId: "getFIRById"
      parameters:
      - name: "FIRId"
        in: "path"
        description: "ID of the FIR to return"
        required: true
        type: "integer"
        format: "int32"
      security:
      - oauth2: [global]
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
             $ref: "#/definitions/FIR"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Complaint not found"
    delete:
      tags:
      - "FIRComplaints"
      summary: "Delete Complaint by id"
      operationId: "deleteFIRById"
      parameters:
      - name: "FIRId"
        in: "path"
        description: "ID of the Complaint to delete"
        required: true
        type: "integer"
        format: "int32"
      security:
      - oauth2: [global]
      responses:
        204:
          description: "Complaint has been successfully removed from box"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Complaint not found"
securityDefinitions:
  oauth2:
    type: "oauth2"
    authorizationUrl: "http://localhost:8080/auth/realms/master/protocol/openid-connect/auth"
    tokenUrl: "http://localhost:8080/auth/realms/master/protocol/openid-connect/token"
    flow: "accessCode"
    scopes:
      global: "global"
definitions:
  FIR:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      district:
        type: "string"
      state:
        type: "string"
      policeStation:
        type: "string"
      fIRno:
        type: "string"
      date:
        type: "string"
      act1:
        type: "string"
      sections1:
        type: "string"
      act2:
        type: "string"
      sections2:
        type: "string"
      act3:
        type: "string"
      sections3:
        type: "string"
      otherActsAndSections:
        type: "string"
      occurenceDay:
        type: "string"
      occurenceDate:
        type: "string"
      occurenceTime:
        type: "string"
      informatioReceivedDate: 
        type: "string"
      informatioReceivedTime: 
        type: "string"
      diaryReferenceEntryNo: 
        type: "string"
      diaryReferenceTime: 
        type: "string"
      written: 
        type: "string"
      oral: 
        type: "string"
      directionAndDistncefromPS:
        type: "string"
      beatNo: 
        type: "string"
      address: 
        type: "string"
      outsideNameofPSAndDistrict: 
        type: "string"
      complainantName: 
        type: "string"
      complainantFatherorHusbandName: 
        type: "string"
      complainantDateOfBirth: 
       type: "string"
      complainantNationality: 
        type: "string"
      complainantOccupation: 
        type: "string"
      complainantPassportNo: 
        type: "string"
      complainantDateofIssue: 
        type: "string"
      complainantPlaceOfIssue: 
        type: "string"
      complainantAddress: 
        type: "string"
      detailsOfSuspected: 
        type: "string"
      reasonsforDelay: 
        type: "string"
      particularsOfPropertiesStolenInvolved: 
        type: "string"